function [fitresult, gof] = createFit(PAR_B, depth_B)
%CREATEFIT(PAR_B,DEPTH_B)
%  Create a fit.
%
%  Data for 'exponential fit' fit:
%      X Input : PAR_B
%      Y Output: depth_B
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jun-2021 11:52:36


%% Fit: 'exponential fit'.
[xData, yData] = prepareCurveData( PAR_B, depth_B );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [987.780543687447 -1.04844763092529];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Exponential fit' );
h = plot( fitresult, xData, yData,'LineWidth',2 );
legend( h, 'Data', 'Exponential fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'PAR(umol/(s m^2))', 'Interpreter', 'none' );
ylabel( 'Depth (cm)', 'Interpreter', 'none' );
ax = gca;
ax.YDir = 'reverse' ;
title('Tantare Basin 4','FontSize',12,'FontName','Times New Roman','FontWeight','bold')
grid on


